<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="annotationPart1.TestNGDemo3" tests="3" time="83.762" ignored="4" failures="2" timestamp="10 Aug 2020 14:27:19 GMT" skipped="0" hostname="DESKTOP-OR6VU5V" errors="0">
  <testcase name="Browser" time="45.701" classname="annotationPart1.TestNGDemo3"/>
  <testcase name="Browser" time="16.287" classname="annotationPart1.TestNGDemo3">
    <failure type="java.lang.AssertionError" message="User Not able to login Sucessfully - Invalid Credentails expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User Not able to login Sucessfully - Invalid Credentails expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at annotationPart1.TestNGDemo3.Browser(TestNGDemo3.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Browser -->
  <testcase name="Browser" time="21.774" classname="annotationPart1.TestNGDemo3">
    <failure type="java.lang.AssertionError" message="User Not able to login Sucessfully - Invalid Credentails expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User Not able to login Sucessfully - Invalid Credentails expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at annotationPart1.TestNGDemo3.Browser(TestNGDemo3.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Browser -->
  <testcase name="Cat" classname="annotationPart1.TestNGDemo2">
    <skipped/>
  </testcase> <!-- Cat -->
  <testcase name="App" classname="annotationPart1.TestNGDemo2">
    <skipped/>
  </testcase> <!-- App -->
  <testcase name="Bal" classname="annotationPart1.TestNGDemo2">
    <skipped/>
  </testcase> <!-- Bal -->
  <testcase name="Dog" classname="annotationPart1.TestNGDemo2">
    <skipped/>
  </testcase> <!-- Dog -->
</testsuite> <!-- annotationPart1.TestNGDemo3 -->
